---
title: "ETC5521 Group Presentation"
subtitle: "How are the COVID-19 cases spreading in the Victorian community during 1st May to 30th September 2020?"
team: Beta
author:
  - Mohammed Faizan 
  - Prachi Jaiswal
  - Karan Garg
date: "`r Sys.Date()`"
output: 
  html_document:
    includes:
      before_body: header.html
bibliography: 
- packages.bib
biblio-style: authoryear-comp
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      messages = FALSE, 
                     warning = FALSE, fig.path = "figures", fig.align ="center")

library(tidyverse) 
library(lubridate)
library(plotly)
library(bookdown)
library(knitr)
library(ggthemes)
library(patchwork)
library(readr)
library(kableExtra)
library(tidytext)
library(dygraphs)
library(quantmod)
library(ggrepel)
library(tidyverse)
library(citation)
library(scales)
library(ggbeeswarm)
library(gt)
library(ggthemes)
library(leaflet)
library(DT)
library(sparkline)
library(formattable)
library(RColorBrewer)
library(sugarbag)
library(tsibble)
library(sugrrants)
library(GGally)
library(naniar)
library(tidyr)
library(RefManageR)
library(sf)
library(glue)
library(unglue)
library(xts)
```

```{r}

# lga_covid <- read_csv(here::here("data/VIC_COVID/COVID19 Data Viz LGA Data - lga.csv"))
# 
# postcode_covid <- read_csv(here::here("data/VIC_COVID/COVID19 Data Viz Postcode data - postcode.csv"))
# 
# cases_source <- read_csv(here::here("data/VIC_COVID/NCOV_COVID_Cases_by_Source_20211023.csv"))
# 
# lga_cases <- read_csv(here::here("data/VIC_COVID/NCOV_COVID_Cases_by_LGA_20211023.csv"))

covid_cases0 <- read_csv(here::here("data/VIC_COVID/NCOV_COVID_Cases_by_LGA_Source_20211023.csv")) %>% mutate(diagnosis_date=ymd(diagnosis_date)) %>% arrange(diagnosis_date)
covid_age <- read_csv(here::here("data/VIC_COVID/NCOV_COVID_Cases_by_Age_Group_20211023.csv"))%>% mutate(diagnosis_date=ymd(diagnosis_date)) %>% arrange(diagnosis_date) 

covid_cases <-  cbind(covid_cases0,covid_age %>% select(agegroup)) %>% 
  filter(diagnosis_date>="2020-05-01") %>% 
  filter(diagnosis_date<="2020-09-30")

```


```{r}
data_path <- here::here("data/shape/boundaries/esrishape/whole_of_dataset/victoria/VMADMIN/")

postcode_boundaries <- read_sf(here::here(glue(data_path, "POSTCODE_POLYGON.shp"))) 

lga_boundaries <- read_sf(here::here(glue(data_path, "AD_LGA_AREA_POLYGON.shp")))%>% filter(STATE=="VIC")
```

```{r}
postcodes <- as_tibble(postcode_boundaries) %>% select(-geometry)
lga <- as_tibble(lga_boundaries)%>% select(-geometry)
```


```{r}
  ggplot(data=postcode_boundaries) +
  geom_sf(mapping = aes(geometry= geometry)) +
  geom_sf_text(aes(geometry= geometry,label=POSTCODE, colour="white"), 
               check_overlap=TRUE)+
  theme_void() 

```
```{r}
date_case <-covid_cases %>% group_by(diagnosis_date) %>% summarise(n_cases = n())

age <-covid_cases %>% group_by(diagnosis_date, agegroup) %>% summarise(n_cases = n())

acquired <-covid_cases %>% group_by(diagnosis_date, acquired) %>% summarise(n_cases = n())

pl <-covid_cases %>% group_by(diagnosis_date, Postcode, Localgovernmentarea) %>% summarise(n_cases = n())

pl_age <-covid_cases %>% group_by(diagnosis_date, Postcode, Localgovernmentarea, agegroup) %>% summarise(n_cases = n())

```

