---
title: "ETC5521 Group Presentation"
subtitle: "How are the COVID-19 cases spreading in the Victorian community during 1st May to 30th September 2020?"
author: "Karan Garg, Mohammed Faizan, Prachi Jaiswal"
institute: "Master of Business Analytics, Monash University"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: [xaringan-themer.css, style.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      navigation:
        scroll: false 
        touch: true
        click: false
        ratio: 16:9
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      messages = FALSE, 
                     warning = FALSE, fig.path = "figures", fig.align ="center")

library(tidyverse) 
library(lubridate)
library(plotly)
library(bookdown)
library(knitr)
library(ggthemes)
library(patchwork)
library(readr)
library(kableExtra)
library(tidytext)
library(dygraphs)
library(quantmod)
library(ggrepel)
library(tidyverse)
library(citation)
library(scales)
library(ggbeeswarm)
library(gt)
library(ggthemes)
library(leaflet)
library(DT)
library(sparkline)
library(formattable)
library(RColorBrewer)
library(sugarbag)
library(tsibble)
library(sugrrants)
library(GGally)
library(naniar)
library(tidyr)
library(RefManageR)
library(xts)

options(htmltools.dir.version = FALSE)

```

```{r writing_packages_bibliographies}
knitr::write_bib(c(.packages()), "packages.bib")
```

```{r}
BibOptions(
  check.entries = FALSE, 
  bib.style = "authoryear", 
  cite.style = "authoryear", 
  style = "markdown",
  hyperlink = FALSE, 
  dashed = FALSE)
myBib = ReadBib(here::here("reference.bib"))
```



